# Generated by Django 3.0.6 on 2020-06-10 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_remove_project_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Project',
        ),
    ]
