# Generated by Django 3.0.5 on 2020-05-07 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_userprofile_employee_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='work_shift',
            field=models.IntegerField(default=2),
        ),
    ]
